-- Author: Tarun (tarungovindk) nvim configs --
--require "user.nvim_tree" 
require "user.cmp"
require "user.alpha"
require "user.toggleterm"
require "user.telescope"
require "user.whichkey"
require "user.ufo"
require "user.mason"
require "user.venn"
