#!/usr/bin/env sh

# Author: tarungovindk yabai tiling window manager config for mac

##  -- config outline taken from --
##  https://www.joshmedeski.com/posts/blazing-fast-window-management-on-macos/

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
# NOTE: for OBS floating head
# yabai -m config left_padding                 450
yabai -m config right_padding                0
yabai -m config window_gap                   0

# apps to not manage (ignore)
yabai -m rule --add app="Cisco Secure Client" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Wally$" manage=off
yabai -m rule --add app="^Pika$" manage=off
yabai -m rule --add app="^balenaEtcher$" manage=off
yabai -m rule --add app="^Creative Cloud$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
abai -m rule --add app="Raycast" manage=off
# yabai -m rule --add app="Raycast" layout=float window_opacity=on opacity=0.5
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="PCoIPClient" manage=off
yabai -m rule --add app="Anyware Client" manage=off
yabai -m rule --add app="Shortcuts" manage=off

echo "yabai configuration loaded.."
